---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-pvc
  namespace: cicd-devsec-ops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem

