apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cicd-devsec-ops-listener
  namespace: cicd-devsec-ops
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: cicd-devsec-ops
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: GIT_HOOK_SECRET
          secretName: cicd-devsec-ops-githook-secret
      - name: validEvents
        value:
        - issue_comment
      ref:
        apiVersion: triggers.tekton.dev
        kind: ClusterInterceptor
        name: gitea
    name: cicd-devsec-ops-trigger
    template:
      ref: cicd-devsec-ops
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: cicd-devsec-ops-listener
  name: el-cicd-devsec-ops-listener
  namespace: cicd-devsec-ops
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-cicd-devsec-ops-listener
    weight: 100
  wildcardPolicy: None

