apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
  name: cicd-devsec-ops
  namespace: cicd-devsec-ops
spec:
  params:
  - description: Pull request number
    name: pr-number
  - name: GIT_REPO
  - name: GIT_REVISION
  - name: GIT_REPO_NAME
  - name: GIT_REPO_FULL_NAME
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cicd-devsec-ops-
      labels:
        app-name: cicd-devsec-ops
    spec:
      params:
        - name: pr-number
          value: $(tt.params.pr-number)
        - name: IMAGE_REPO
          value: "quay.io/feven" # TO update
        - name: UI_BASE_PATH
          value: "https://console.openshift-console.svc.cluster.local/k8s/ns/cicd-devsec-ops/tekton.dev~v1beta1~Pipeline/clone-build-push/Runs"
        - name: GIT_REPO
          value: $(tt.params.GIT_REPO)
        - name: GIT_REVISION
          value: $(tt.params.GIT_REVISION)
        - name: GIT_REPO_NAME
          value: $(tt.params.GIT_REPO_NAME)
        - name: GIT_REPO_FULL_NAME
          value: $(tt.params.GIT_REPO_FULL_NAME)
        - name: GITEA_HOST_URL
          value: "gitea-gitea.apps.cluster-k4q4d.k4q4d.sandbox1890.opentlc.com" # Base Domain to update
        - name: GITEA_HTTPS_OR_HTTP
          value: https
        - name: GITEA_TOKEN_SECRET_NAME
          value: gitea-bot-token
        - name: GITEA_TOKEN_SECRET_KEY
          value: token
      pipelineRef:
        name: clone-build-push
      serviceAccountName: build-bot
      timeout: 1h0m0s
      workspaces:
        - name: tekton-pvc
          persistentVolumeClaim:
            claimName: tekton-pvc
        - name: dockerconfig
          secret:
            secretName: registry-credentials
